version: '2'

services:

  nginx:
    image: prooph/nginx:www
    ports:
      - 8080:80
      - 443:443
      - 10081:10081
      - 10082:10082
    volumes:
      - ./gateway/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./gateway/config:/etc/nginx/config:ro

  php-todo-write:
    image: prooph/php:7.1-fpm
    volumes:
      - ./service/todo-write:/var/www

  php-todo-read:
    image: prooph/php:7.1-fpm
    volumes:
      - ./service/todo-read:/var/www

  php-user-write:
    image: prooph/php:7.1-fpm
    volumes:
      - ./service/user-write:/var/www
    environment:
      - PDO_DSN=pgsql:host=postgres port=5432 dbname=micro_do
      - PDO_USER=postgres
      - PDO_PWD=
      - MONGO_SERVER=mongodb://mongodb:27017
      - MONGO_DB_NAME=micro_do

  php-user-read:
    image: prooph/php:7.1-fpm
    volumes:
      - ./service/user-read:/var/www

  php-user-snapshotter:
    image: prooph/php:7.1-cli
    volumes:
      - ./service/user-write:/app
    environment:
      - PDO_DSN=pgsql:host=postgres port=5432 dbname=micro_do
      - PDO_USER=postgres
      - PDO_PWD=
      - MONGO_SERVER=mongodb://mongodb:27017
      - MONGO_DB_NAME=micro_do
    command: php /app/bin/user_snapshotter.php

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=micro_do
    volumes:
      - ./env/postgres/initdb.d:/docker-entrypoint-initdb.d:ro

  mongodb:
    image: mongo
    ports:
      - 27017:27017
